FORBIDDEN = '_'
READ_ONLY = 'r_o'
WRITE_ONLY = 'w_o'
READ_AND_WRITE = 'r_w'
SHARED = 'shared'
PERMISSIONS = (
    (FORBIDDEN, 'FORBIDDEN'),
    (READ_ONLY, 'READ_ONLY'),
    (WRITE_ONLY,'WRITE_ONLY'),
    (READ_AND_WRITE,'READ_AND_WRITE') 
)