# Generated by Django 2.1.1 on 2018-10-06 13:22

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import kernel.utils.upload_to


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.KERNEL_PERSON_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removed', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('upload', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/personal_files'), upload_to=kernel.utils.upload_to.UploadTo('', '', file_manager=True))),
                ('is_public', models.BooleanField(default=False)),
                ('file_name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removed', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('space', models.IntegerField(default=1024)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='folder_user', to=settings.KERNEL_PERSON_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='file',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_filemanager.Folder'),
        ),
    ]
