# Generated by Django 3.0.3 on 2020-09-18 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_filemanager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='space',
        ),
        migrations.AddField(
            model_name='folder',
            name='content_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='folder',
            name='max_space',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='name',
            field=models.CharField(default='undefined folder', max_length=255),
        ),
        migrations.AddField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='django_filemanager.Folder'),
        ),
        migrations.AddField(
            model_name='folder',
            name='permission',
            field=models.CharField(choices=[('_', 'FORBIDDEN'), ('r_o', 'READ_ONLY'), ('w_o', 'WRITE_ONLY'), ('r_w', 'READ_AND_WRITE')], default='r_o', max_length=10),
        ),
        migrations.AddField(
            model_name='folder',
            name='root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_folders', to='django_filemanager.Folder'),
        ),
        migrations.AddField(
            model_name='folder',
            name='starred',
            field=models.BooleanField(default=False),
        ),
    ]
