# Generated by Django 3.0.3 on 2020-12-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_filemanager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemanager',
            name='filemanager_access_roles',
        ),
        migrations.AddField(
            model_name='filemanager',
            name='filemanager_access_permissions',
            field=models.TextField(default='true'),
            preserve_default=False,
        ),
    ]
