# Generated by Django 3.0.3 on 2021-03-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_filemanager', '0002_auto_20210108_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='share_with_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='folder',
            name='share_with_all',
            field=models.BooleanField(default=False),
        ),
    ]
