# Generated by Django 3.0.3 on 2020-09-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_filemanager', '0003_auto_20200918_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_name',
        ),
        migrations.AddField(
            model_name='file',
            name='extension',
            field=models.CharField(default='undefined', max_length=10),
        ),
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(default='undedfined file', max_length=50),
        ),
        migrations.AddField(
            model_name='file',
            name='permission',
            field=models.CharField(choices=[('_', 'FORBIDDEN'), ('r_o', 'READ_ONLY'), ('w_o', 'WRITE_ONLY'), ('r_w', 'READ_AND_WRITE')], default='r_o', max_length=10),
        ),
        migrations.AddField(
            model_name='file',
            name='size',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
