# Generated by Django 3.0.3 on 2020-09-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_filemanager', '0004_auto_20200920_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='content_size',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='max_space',
            field=models.IntegerField(null=True),
        ),
    ]
