# Generated by Django 3.0.3 on 2020-09-21 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_filemanager', '0004_auto_20200919_1540'),
        ('django_filemanager', '0005_auto_20200921_1820'),
    ]

    operations = [
    ]
